# Meta
name: "dataset2vec"

# Data
train_data_path: "data/openml/encoder_training_data/train"
train_batch_size: 16
train_n_batches: 100

val_data_path: "data/openml/encoder_training_data/val"
val_batch_size: 512

# Model
f_dense_hidden_size: 16
f_res_hidden_size: 16
f_res_n_hidden: 3
f_dense_out_hidden_size: 16
f_block_repetitions: 3
g_layers_sizes: [32, 16, 8]
h_dense_hidden_size: 32
h_res_hidden_size: 32
h_res_n_hidden: 3
h_dense_out_hidden_size: 16
h_block_repetitions: 3

# Trainer
gamma: 1
learning_rate: 0.0001
weight_decay: 0.0001
max_epochs: 10000
check_val_every_n_epoch: 5
early_stopping_patience: 100