name: "liltab_encoder_training"
num_epochs: 100000
learning_rate: 0.0001
weight_decay: 0
batch_size: 37
gradient_clipping: False
early_stopping_intervals: 25
representation_penalty_weight: 0

support_size: 3
query_size: 29

hidden_representation_size: 32
n_hidden_layers: 3
hidden_size: 32
dropout_rate: 0.1
is_classifier: True

train_data_path: data/openml/encoder_training_data/train
val_data_path: data/openml/encoder_training_data/val
